language: node_js

node_js:
  - node

before_script:
  - yarn global add grunt-cli eslint codecov

script:
  - npm run test

after_script:
  - codecov

notifications:
  email:
    on_success: never

sudo: false
